project_id = "wksyyydmgpcaxdijalqf"

[functions.send-notification-email]
verify_jwt = false

[functions.og-network]
verify_jwt = false

[functions.send-invite-email]
verify_jwt = false

[functions.api-proxy]
verify_jwt = false

[functions.sql-generate]
verify_jwt = false