// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wksyyydmgpcaxdijalqf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indrc3l5eWRtZ3BjYXhkaWphbHFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0MzcwMzAsImV4cCI6MjA2OTAxMzAzMH0.Rh37M5IDPo8uGBucIwWdZk79o8rpxhs8SQ9ACohDUQ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});